import type { Metadata } from "next";
import "@/app/styles/globals.css";
import { geistMono, geistSans } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Flash Cardos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
